const ActionTypes = {
  // LOAD_WEATHER_REQUEST: 'LOAD_WEATHER_REQUEST',
  LOAD_WEATHER_SUCCESS: 'LOAD_WEATHER_SUCCESS',
  LOAD_WEATHER_FAIL: 'LOAD_WEATHER_FAIL',
  TOGGLE_LOADING_PAGE: 'TOGGLE_LOADING_PAGE'
};

export default ActionTypes;
